name: TeamSphere General Checks and Tests
on:
    push:
        branches-ignore:
            - master
        tags-ignore:
            - '**'

jobs:
    test:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup JDK
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: corretto

            - name: Make mvnw executable
              run: chmod +x ./mvnw

            - name: Running Unit Tests
              run: ./mvnw clean compile install

    checkstyle:
        name: Run Linter
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup JDK
              uses: actions/setup-java@v4
              with:
                  distribution: corretto
                  java-version: '21'

            - name: Run Checkstyle
              run: mvn checkstyle:check
